//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bkp_tbl_bp_permission
    {
        public string BP_USER { get; set; }
        public string JOB_NO { get; set; }
        public Nullable<int> BP_READ { get; set; }
        public Nullable<int> BP_WRITE { get; set; }
        public Nullable<int> MN_READ { get; set; }
        public Nullable<int> MN_WRITE { get; set; }
        public Nullable<int> PJ_READ { get; set; }
        public Nullable<int> PJ_WRITE { get; set; }
    }
}
