//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BusinessPlanEntities : DbContext
    {
        public BusinessPlanEntities()
            : base("name=BusinessPlanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMMENT> COMMENTS { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<MAIL> MAILs { get; set; }
        public virtual DbSet<TBL_BP_ADJYEAR> TBL_BP_ADJYEAR { get; set; }
        public virtual DbSet<TBL_BP_CLIENT> TBL_BP_CLIENT { get; set; }
        public virtual DbSet<TBL_BP_DICTIONARY> TBL_BP_DICTIONARY { get; set; }
        public virtual DbSet<TBL_BP_DIVISION> TBL_BP_DIVISION { get; set; }
        public virtual DbSet<TBL_BP_LOCATION> TBL_BP_LOCATION { get; set; }
        public virtual DbSet<TBL_BP_PERMISSION> TBL_BP_PERMISSION { get; set; }
        public virtual DbSet<TBL_BP_POSTED> TBL_BP_POSTED { get; set; }
        public virtual DbSet<TBL_BP_RESOURCE> TBL_BP_RESOURCE { get; set; }
        public virtual DbSet<TBL_BP_RESOURCE_> TBL_BP_RESOURCE_ { get; set; }
        public virtual DbSet<TBL_BP_REVISION> TBL_BP_REVISION { get; set; }
        public virtual DbSet<TBL_BP_USERMASTER> TBL_BP_USERMASTER { get; set; }
        public virtual DbSet<TBL_MN_ACTUALS> TBL_MN_ACTUALS { get; set; }
        public virtual DbSet<TBL_MN_APPROVAL> TBL_MN_APPROVAL { get; set; }
        public virtual DbSet<TBL_MN_BPLAN> TBL_MN_BPLAN { get; set; }
        public virtual DbSet<TBL_MN_COMMENTS> TBL_MN_COMMENTS { get; set; }
        public virtual DbSet<TBL_MN_HEADS> TBL_MN_HEADS { get; set; }
        public virtual DbSet<TBL_MN_LOG> TBL_MN_LOG { get; set; }
        public virtual DbSet<TBL_MN_PERIOD> TBL_MN_PERIOD { get; set; }
        public virtual DbSet<TBL_MN_POSTED> TBL_MN_POSTED { get; set; }
        public virtual DbSet<TBL_MN_PROJECTION> TBL_MN_PROJECTION { get; set; }
        public virtual DbSet<TBL_MN_PROVISION> TBL_MN_PROVISION { get; set; }
        public virtual DbSet<TBL_MN_USERMAP> TBL_MN_USERMAP { get; set; }
        public virtual DbSet<TBL_MN_WORKDONE> TBL_MN_WORKDONE { get; set; }
        public virtual DbSet<TBL_PJ_POSTED> TBL_PJ_POSTED { get; set; }
        public virtual DbSet<TBL_RESOURCE_GLOBAL> TBL_RESOURCE_GLOBAL { get; set; }
        public virtual DbSet<TBL_RV_ACTIVE> TBL_RV_ACTIVE { get; set; }
        public virtual DbSet<TBL_RV_BPLAN> TBL_RV_BPLAN { get; set; }
        public virtual DbSet<TBL_RV_DICTIONARY> TBL_RV_DICTIONARY { get; set; }
        public virtual DbSet<TBL_RV_MASTER> TBL_RV_MASTER { get; set; }
        public virtual DbSet<TBL_RV_RESOURCE> TBL_RV_RESOURCE { get; set; }
        public virtual DbSet<TBL_RV_RESOURCE_> TBL_RV_RESOURCE_ { get; set; }
        public virtual DbSet<VOWDH> VOWDHS { get; set; }
        public virtual DbSet<bkp_tbl_bp_permission> bkp_tbl_bp_permission { get; set; }
        public virtual DbSet<TBL_MN_LOGAPPROVAL> TBL_MN_LOGAPPROVAL { get; set; }
        public virtual DbSet<TBL_MN_PROJECTION_BACKUP> TBL_MN_PROJECTION_BACKUP { get; set; }
        public virtual DbSet<TBL_RESOURCE_GLOBAL_BIN> TBL_RESOURCE_GLOBAL_BIN { get; set; }
        public virtual DbSet<vw_Users> vw_Users { get; set; }
    
        public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual ObjectResult<GET_APPROVALSTATUS_Result> GET_APPROVALSTATUS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_APPROVALSTATUS_Result>("GET_APPROVALSTATUS");
        }
    
        public virtual ObjectResult<PROC_BP_ADJYEAR_Result> PROC_BP_ADJYEAR(Nullable<int> bP_YEAR, string jOB_NO, string rESO_TYPE)
        {
            var bP_YEARParameter = bP_YEAR.HasValue ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(int));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var rESO_TYPEParameter = rESO_TYPE != null ?
                new ObjectParameter("RESO_TYPE", rESO_TYPE) :
                new ObjectParameter("RESO_TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_BP_ADJYEAR_Result>("PROC_BP_ADJYEAR", bP_YEARParameter, jOB_NOParameter, rESO_TYPEParameter);
        }
    
        public virtual int PROC_BP_INTER_UNIT_INCOME_UPDATE(Nullable<long> bP_YEAR, Nullable<int> uPDATE, string jOBNO)
        {
            var bP_YEARParameter = bP_YEAR.HasValue ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(long));
    
            var uPDATEParameter = uPDATE.HasValue ?
                new ObjectParameter("UPDATE", uPDATE) :
                new ObjectParameter("UPDATE", typeof(int));
    
            var jOBNOParameter = jOBNO != null ?
                new ObjectParameter("JOBNO", jOBNO) :
                new ObjectParameter("JOBNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_INTER_UNIT_INCOME_UPDATE", bP_YEARParameter, uPDATEParameter, jOBNOParameter);
        }
    
        public virtual int PROC_BP_REPT_3YEAR(string bP_YEAR, string jOB_NO)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_3YEAR", bP_YEARParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_BP_REPT_CUMGRP(string bP_YEAR, string jOB_NO, string jOBTP)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_CUMGRP", bP_YEARParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_BP_REPT_DISTRIBUTION(string bP_YEAR, string jOB_NO, string jOBTP)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_DISTRIBUTION", bP_YEARParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_BP_REPT_DIVISION(string bP_YEAR, string jOB_NO, string jOBTP)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_DIVISION", bP_YEARParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_BP_REPT_DIVISIONSUMMARY(string bP_YEAR, string jOB_NO)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_DIVISIONSUMMARY", bP_YEARParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_BP_REPT_EXGLANCE(string bP_YEAR, string jOB_NO, string jOBTP)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_EXGLANCE", bP_YEARParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_BP_REPT_JOBWISE(string bP_YEAR, string jOB_NO, string jOBTP)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_JOBWISE", bP_YEARParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_BP_REPT_JOBWISESUMMARY(string bP_YEAR, string jOB_NO)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_JOBWISESUMMARY", bP_YEARParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_BP_REPT_MONTHWISE(string bP_YEAR, string jOB_NO)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_MONTHWISE", bP_YEARParameter, jOB_NOParameter);
        }
    
        public virtual ObjectResult<PROC_BP_REPT_MPSUMMARY_Result> PROC_BP_REPT_MPSUMMARY(string bP_YEAR, string rESO_TYPE, string jOB_NO, string jOBTP)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var rESO_TYPEParameter = rESO_TYPE != null ?
                new ObjectParameter("RESO_TYPE", rESO_TYPE) :
                new ObjectParameter("RESO_TYPE", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_BP_REPT_MPSUMMARY_Result>("PROC_BP_REPT_MPSUMMARY", bP_YEARParameter, rESO_TYPEParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_BP_REPT_QUARTERWISE(string bP_YEAR, string jOB_NO)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_QUARTERWISE", bP_YEARParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_BP_REPT_REVISION(string iTM_YEAR, string jOB_NO)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_REVISION", iTM_YEARParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_BP_REPT_REVISIONQRT(string iTM_YEAR, string jOB_NO)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_REVISIONQRT", iTM_YEARParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_BP_REPT_TOVER(string bP_YEAR, string jOB_NO, string jOBTP)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_TOVER", bP_YEARParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_BP_REPT_WLOAD(string bP_YEAR, string jOB_NO, string jOBTP)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_REPT_WLOAD", bP_YEARParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual ObjectResult<PROC_BP_SHOW_MASTER_Result> PROC_BP_SHOW_MASTER(string rESO_TYPE)
        {
            var rESO_TYPEParameter = rESO_TYPE != null ?
                new ObjectParameter("RESO_TYPE", rESO_TYPE) :
                new ObjectParameter("RESO_TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_BP_SHOW_MASTER_Result>("PROC_BP_SHOW_MASTER", rESO_TYPEParameter);
        }
    
        public virtual ObjectResult<PROC_BP_SHOW_PERMISSION_Result> PROC_BP_SHOW_PERMISSION(string bP_USER)
        {
            var bP_USERParameter = bP_USER != null ?
                new ObjectParameter("BP_USER", bP_USER) :
                new ObjectParameter("BP_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_BP_SHOW_PERMISSION_Result>("PROC_BP_SHOW_PERMISSION", bP_USERParameter);
        }
    
        public virtual ObjectResult<PROC_BP_SHOW_RESOURCE_Result> PROC_BP_SHOW_RESOURCE(Nullable<int> bP_YEAR, string jOB_NO, string rESO_TYPE)
        {
            var bP_YEARParameter = bP_YEAR.HasValue ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(int));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var rESO_TYPEParameter = rESO_TYPE != null ?
                new ObjectParameter("RESO_TYPE", rESO_TYPE) :
                new ObjectParameter("RESO_TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_BP_SHOW_RESOURCE_Result>("PROC_BP_SHOW_RESOURCE", bP_YEARParameter, jOB_NOParameter, rESO_TYPEParameter);
        }
    
        public virtual ObjectResult<PROC_BP_SHOW_SRCHJOB_Result> PROC_BP_SHOW_SRCHJOB(string sRCHTX)
        {
            var sRCHTXParameter = sRCHTX != null ?
                new ObjectParameter("SRCHTX", sRCHTX) :
                new ObjectParameter("SRCHTX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_BP_SHOW_SRCHJOB_Result>("PROC_BP_SHOW_SRCHJOB", sRCHTXParameter);
        }
    
        public virtual int PROC_BP_TRANINTERNAL(string jOB_NO, Nullable<int> bP_YEAR)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var bP_YEARParameter = bP_YEAR.HasValue ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_TRANINTERNAL", jOB_NOParameter, bP_YEARParameter);
        }
    
        public virtual int PROC_BP_UPDATE_CONTRACTVALUE(string jOB_NO, Nullable<decimal> vOWD, Nullable<decimal> pVOWD)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var vOWDParameter = vOWD.HasValue ?
                new ObjectParameter("VOWD", vOWD) :
                new ObjectParameter("VOWD", typeof(decimal));
    
            var pVOWDParameter = pVOWD.HasValue ?
                new ObjectParameter("PVOWD", pVOWD) :
                new ObjectParameter("PVOWD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_UPDATE_CONTRACTVALUE", jOB_NOParameter, vOWDParameter, pVOWDParameter);
        }
    
        public virtual int PROC_BP_UPDATE_PERMISSION(string jOB_NO)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_BP_UPDATE_PERMISSION", jOB_NOParameter);
        }
    
        public virtual ObjectResult<PROC_MN_LOGAPPROVAL_Result> PROC_MN_LOGAPPROVAL(string jOB_NO, Nullable<int> pOST_MONTH, Nullable<int> pOST_YEAR)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var pOST_MONTHParameter = pOST_MONTH.HasValue ?
                new ObjectParameter("POST_MONTH", pOST_MONTH) :
                new ObjectParameter("POST_MONTH", typeof(int));
    
            var pOST_YEARParameter = pOST_YEAR.HasValue ?
                new ObjectParameter("POST_YEAR", pOST_YEAR) :
                new ObjectParameter("POST_YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_MN_LOGAPPROVAL_Result>("PROC_MN_LOGAPPROVAL", jOB_NOParameter, pOST_MONTHParameter, pOST_YEARParameter);
        }
    
        public virtual ObjectResult<PROC_MN_REPT_4MONTH_Result> PROC_MN_REPT_4MONTH(string iTM_YEAR, string iTM_MONTH, string jOB_NO, string jOBTP)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_MN_REPT_4MONTH_Result>("PROC_MN_REPT_4MONTH", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_MN_REPT_4MONTH_CHAIRMAN(string iTM_YEAR, string iTM_MONTH, string jOB_NO, string jOBTP)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_4MONTH_CHAIRMAN", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_MN_REPT_4MONTH_INTERNAL(string iTM_YEAR, string iTM_MONTH, string jOB_NO)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_4MONTH_INTERNAL", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_MN_REPT_4MONTH_REVISION(string iTM_YEAR, string iTM_MONTH, string jOB_NO, string jOBTP)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_4MONTH_REVISION", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual ObjectResult<PROC_MN_REPT_BPAVARIANCE_Result> PROC_MN_REPT_BPAVARIANCE(string iTM_YEAR, string iTM_MONTH, string jOB_NO)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_MN_REPT_BPAVARIANCE_Result>("PROC_MN_REPT_BPAVARIANCE", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_MN_REPT_CUMDIVISION(string iTM_YEAR, string iTM_MONTH, string jOB_NO, string jOBTP)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_CUMDIVISION", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_MN_REPT_DIVISION(string iTM_YEAR, string iTM_MONTH, string jOB_NO, string jOBTP)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_DIVISION", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual ObjectResult<PROC_MN_REPT_GE4MONTH_Result> PROC_MN_REPT_GE4MONTH(string iTM_YEAR, string iTM_MONTH, string jOB_NO)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_MN_REPT_GE4MONTH_Result>("PROC_MN_REPT_GE4MONTH", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_MN_REPT_JB4CUMULATIVE(string iTM_YEAR, string iTM_MONTH, string jOB_NO)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_JB4CUMULATIVE", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter);
        }
    
        public virtual ObjectResult<PROC_MN_REPT_JB4MONTH_Result> PROC_MN_REPT_JB4MONTH(string iTM_YEAR, string iTM_MONTH, string jOB_NO, string jOBTP)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_MN_REPT_JB4MONTH_Result>("PROC_MN_REPT_JB4MONTH", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_MN_REPT_JOB4CUMULATIVE(string iTM_YEAR, string jOB_LIST)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var jOB_LISTParameter = jOB_LIST != null ?
                new ObjectParameter("JOB_LIST", jOB_LIST) :
                new ObjectParameter("JOB_LIST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_JOB4CUMULATIVE", iTM_YEARParameter, jOB_LISTParameter);
        }
    
        public virtual int PROC_MN_REPT_JOBACTUALYEARWISE(string jOB_NO)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_JOBACTUALYEARWISE", jOB_NOParameter);
        }
    
        public virtual int PROC_MN_REPT_JOBSUMYEARTOMONTH(string iTM_YEAR, string iTM_MONTH, string jOBTP, string jOB_LIST)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            var jOB_LISTParameter = jOB_LIST != null ?
                new ObjectParameter("JOB_LIST", jOB_LIST) :
                new ObjectParameter("JOB_LIST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_JOBSUMYEARTOMONTH", iTM_YEARParameter, iTM_MONTHParameter, jOBTPParameter, jOB_LISTParameter);
        }
    
        public virtual int PROC_MN_REPT_JOBTODATE(string jOB_LIST)
        {
            var jOB_LISTParameter = jOB_LIST != null ?
                new ObjectParameter("JOB_LIST", jOB_LIST) :
                new ObjectParameter("JOB_LIST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_JOBTODATE", jOB_LISTParameter);
        }
    
        public virtual int PROC_MN_REPT_JOBTODATE___(string jOB_LIST)
        {
            var jOB_LISTParameter = jOB_LIST != null ?
                new ObjectParameter("JOB_LIST", jOB_LIST) :
                new ObjectParameter("JOB_LIST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_JOBTODATE___", jOB_LISTParameter);
        }
    
        public virtual int PROC_MN_REPT_PROJECTROLLUP(string jOB_NO, Nullable<int> iTM_YEAR, Nullable<int> iTM_MONTH, string nT_USER)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var iTM_YEARParameter = iTM_YEAR.HasValue ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(int));
    
            var iTM_MONTHParameter = iTM_MONTH.HasValue ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(int));
    
            var nT_USERParameter = nT_USER != null ?
                new ObjectParameter("NT_USER", nT_USER) :
                new ObjectParameter("NT_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_PROJECTROLLUP", jOB_NOParameter, iTM_YEARParameter, iTM_MONTHParameter, nT_USERParameter);
        }
    
        public virtual ObjectResult<PROC_MN_REPT_PROVISION_Result> PROC_MN_REPT_PROVISION(Nullable<int> iTM_YEAR, Nullable<int> iTM_MONTH, string jOB_NO)
        {
            var iTM_YEARParameter = iTM_YEAR.HasValue ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(int));
    
            var iTM_MONTHParameter = iTM_MONTH.HasValue ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(int));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_MN_REPT_PROVISION_Result>("PROC_MN_REPT_PROVISION", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_MN_REPT_QUARTER_CHAIRMAN(string iTM_YEAR, string jOB_NO, string jOBTP)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_QUARTER_CHAIRMAN", iTM_YEARParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_MN_REPT_QUARTERWISE(string iTM_YEAR, string iTM_MONTH, string jOB_NO, string jOBTP)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var jOBTPParameter = jOBTP != null ?
                new ObjectParameter("JOBTP", jOBTP) :
                new ObjectParameter("JOBTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_QUARTERWISE", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter, jOBTPParameter);
        }
    
        public virtual int PROC_MN_REPT_TOPSHEET_CHAIRMAN(string iTM_YEAR, string iTM_MONTH, string jOB_NO)
        {
            var iTM_YEARParameter = iTM_YEAR != null ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(string));
    
            var iTM_MONTHParameter = iTM_MONTH != null ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_REPT_TOPSHEET_CHAIRMAN", iTM_YEARParameter, iTM_MONTHParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_MN_SHOW_APPROVEWD(string jOB_NO, Nullable<int> iTM_YEAR, Nullable<int> iTM_MONTH, string nT_USER)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var iTM_YEARParameter = iTM_YEAR.HasValue ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(int));
    
            var iTM_MONTHParameter = iTM_MONTH.HasValue ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(int));
    
            var nT_USERParameter = nT_USER != null ?
                new ObjectParameter("NT_USER", nT_USER) :
                new ObjectParameter("NT_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_SHOW_APPROVEWD", jOB_NOParameter, iTM_YEARParameter, iTM_MONTHParameter, nT_USERParameter);
        }
    
        public virtual ObjectResult<string> PROC_MN_SHOW_PDESCRIPTION(string jOB_NO)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_MN_SHOW_PDESCRIPTION", jOB_NOParameter);
        }
    
        public virtual int PROC_MN_SHOW_PORA(string pORA, string jOB_NO, Nullable<int> iTM_YEAR)
        {
            var pORAParameter = pORA != null ?
                new ObjectParameter("PORA", pORA) :
                new ObjectParameter("PORA", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var iTM_YEARParameter = iTM_YEAR.HasValue ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_SHOW_PORA", pORAParameter, jOB_NOParameter, iTM_YEARParameter);
        }
    
        public virtual ObjectResult<PROC_MN_SHOW_PROVISIONS_Result> PROC_MN_SHOW_PROVISIONS(string jOB_NO, string iTM_ID, string iTM_TYPE, Nullable<int> iTM_YEAR, Nullable<int> iTM_MONTH)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var iTM_IDParameter = iTM_ID != null ?
                new ObjectParameter("ITM_ID", iTM_ID) :
                new ObjectParameter("ITM_ID", typeof(string));
    
            var iTM_TYPEParameter = iTM_TYPE != null ?
                new ObjectParameter("ITM_TYPE", iTM_TYPE) :
                new ObjectParameter("ITM_TYPE", typeof(string));
    
            var iTM_YEARParameter = iTM_YEAR.HasValue ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(int));
    
            var iTM_MONTHParameter = iTM_MONTH.HasValue ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_MN_SHOW_PROVISIONS_Result>("PROC_MN_SHOW_PROVISIONS", jOB_NOParameter, iTM_IDParameter, iTM_TYPEParameter, iTM_YEARParameter, iTM_MONTHParameter);
        }
    
        public virtual int PROC_MN_SHOW_WORKDONE(string jOB_NO, Nullable<int> iTM_YEAR)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var iTM_YEARParameter = iTM_YEAR.HasValue ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_SHOW_WORKDONE", jOB_NOParameter, iTM_YEARParameter);
        }
    
        public virtual int PROC_MN_UPDATE_PROVISIONS(string jOB_NO, Nullable<int> iTM_YEAR, Nullable<int> iTM_MONTH)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var iTM_YEARParameter = iTM_YEAR.HasValue ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(int));
    
            var iTM_MONTHParameter = iTM_MONTH.HasValue ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_UPDATE_PROVISIONS", jOB_NOParameter, iTM_YEARParameter, iTM_MONTHParameter);
        }
    
        public virtual int PROC_MN_UPDATE_WORKDONE(string jOB_NO, Nullable<int> iTM_YEAR, Nullable<int> iTM_MONTH)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var iTM_YEARParameter = iTM_YEAR.HasValue ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(int));
    
            var iTM_MONTHParameter = iTM_MONTH.HasValue ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_UPDATE_WORKDONE", jOB_NOParameter, iTM_YEARParameter, iTM_MONTHParameter);
        }
    
        public virtual int PROC_MN_UPDATE_WORKDONE_(string jOB_NO, Nullable<int> iTM_YEAR, Nullable<int> iTM_MONTH)
        {
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            var iTM_YEARParameter = iTM_YEAR.HasValue ?
                new ObjectParameter("ITM_YEAR", iTM_YEAR) :
                new ObjectParameter("ITM_YEAR", typeof(int));
    
            var iTM_MONTHParameter = iTM_MONTH.HasValue ?
                new ObjectParameter("ITM_MONTH", iTM_MONTH) :
                new ObjectParameter("ITM_MONTH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_MN_UPDATE_WORKDONE_", jOB_NOParameter, iTM_YEARParameter, iTM_MONTHParameter);
        }
    
        public virtual int PROC_RV_CREATE_REVISION(Nullable<int> bP_YEAR, Nullable<int> bP_MONTH, ObjectParameter rEV_NO)
        {
            var bP_YEARParameter = bP_YEAR.HasValue ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(int));
    
            var bP_MONTHParameter = bP_MONTH.HasValue ?
                new ObjectParameter("BP_MONTH", bP_MONTH) :
                new ObjectParameter("BP_MONTH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_RV_CREATE_REVISION", bP_YEARParameter, bP_MONTHParameter, rEV_NO);
        }
    
        public virtual int PROC_RV_TRANSFER_REVISION(Nullable<int> bP_YEAR, ObjectParameter rEV_NO)
        {
            var bP_YEARParameter = bP_YEAR.HasValue ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_RV_TRANSFER_REVISION", bP_YEARParameter, rEV_NO);
        }
    
        public virtual int PROC_TEMP_UPDATE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_TEMP_UPDATE");
        }
    
        public virtual int PROC_TRANSFER_2MONITORING(string bP_YEAR)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_TRANSFER_2MONITORING", bP_YEARParameter);
        }
    
        public virtual int PROC_TRANSFER_2MONITORING_LATEST(string bP_YEAR, Nullable<int> bP_MONTH)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var bP_MONTHParameter = bP_MONTH.HasValue ?
                new ObjectParameter("BP_MONTH", bP_MONTH) :
                new ObjectParameter("BP_MONTH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_TRANSFER_2MONITORING_LATEST", bP_YEARParameter, bP_MONTHParameter);
        }
    
        public virtual int PROC_TRANSFER_2REVISION(string bP_YEAR, string jOB_NO)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_TRANSFER_2REVISION", bP_YEARParameter, jOB_NOParameter);
        }
    
        public virtual int PROC_TRANSFER_2REVISION_(string bP_YEAR, string jOB_NO)
        {
            var bP_YEARParameter = bP_YEAR != null ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(string));
    
            var jOB_NOParameter = jOB_NO != null ?
                new ObjectParameter("JOB_NO", jOB_NO) :
                new ObjectParameter("JOB_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_TRANSFER_2REVISION_", bP_YEARParameter, jOB_NOParameter);
        }
    
        public virtual int sp__ObjectBaseJobwiseBreakUP(string rESO_TYPE, Nullable<int> bP_YEAR, string jOBNO)
        {
            var rESO_TYPEParameter = rESO_TYPE != null ?
                new ObjectParameter("RESO_TYPE", rESO_TYPE) :
                new ObjectParameter("RESO_TYPE", typeof(string));
    
            var bP_YEARParameter = bP_YEAR.HasValue ?
                new ObjectParameter("BP_YEAR", bP_YEAR) :
                new ObjectParameter("BP_YEAR", typeof(int));
    
            var jOBNOParameter = jOBNO != null ?
                new ObjectParameter("JOBNO", jOBNO) :
                new ObjectParameter("JOBNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp__ObjectBaseJobwiseBreakUP", rESO_TYPEParameter, bP_YEARParameter, jOBNOParameter);
        }
    
        public virtual int Test()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Test");
        }
    }
}
