//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RV_RESOURCE_
    {
        public int BP_MONTH { get; set; }
        public int BP_YEAR { get; set; }
        public string JOB_NO { get; set; }
        public int REV_NO { get; set; }
        public string RESO_ID { get; set; }
        public string RESO_TYPE { get; set; }
        public Nullable<decimal> RESO_QTY { get; set; }
    }
}
