//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RV_ACTIVE
    {
        public int BP_YEAR { get; set; }
        public Nullable<int> REV_NO { get; set; }
        public Nullable<int> BP_MONTH { get; set; }
        public Nullable<int> MN_REV { get; set; }
    }
}
