//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RV_DICTIONARY
    {
        public int BP_YEAR { get; set; }
        public string JOB_NO { get; set; }
        public int REV_NO { get; set; }
        public Nullable<System.DateTime> SDATE { get; set; }
        public Nullable<System.DateTime> FDATE { get; set; }
        public string JOB_TITLE { get; set; }
        public string DIVISION { get; set; }
        public string BP_MANAGER { get; set; }
        public Nullable<int> MN_PROJECTION { get; set; }
        public Nullable<decimal> JOB_VOWD { get; set; }
        public Nullable<decimal> JOB_PVOWD { get; set; }
        public Nullable<int> MN_CLOSE { get; set; }
        public Nullable<int> BP_OFFSHORE { get; set; }
        public string CLIENT { get; set; }
        public string LOCATION { get; set; }
        public Nullable<decimal> OT_PERCENT { get; set; }
        public Nullable<decimal> FUEL_PERCENT { get; set; }
        public Nullable<decimal> FOOD_STAFF { get; set; }
        public Nullable<decimal> FOOD_WORKER { get; set; }
    }
}
