//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RESOURCE_GLOBAL
    {
        public string RESO_ID { get; set; }
        public string RESO_TYPE { get; set; }
        public string RESO_TITLE { get; set; }
        public string RESO_UNIT { get; set; }
        public Nullable<decimal> RESO_RATE { get; set; }
        public string RESO_PTR { get; set; }
        public Nullable<decimal> ROW_ID { get; set; }
    }
}
