//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BP_DICTIONARY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_BP_DICTIONARY()
        {
            this.TBL_BP_ADJYEAR = new HashSet<TBL_BP_ADJYEAR>();
            this.TBL_BP_RESOURCE = new HashSet<TBL_BP_RESOURCE>();
        }
    
        public int BP_YEAR { get; set; }
        public string JOB_NO { get; set; }
        public Nullable<System.DateTime> SDATE { get; set; }
        public Nullable<System.DateTime> FDATE { get; set; }
        public string JOB_TITLE { get; set; }
        public string DIVISION { get; set; }
        public string BP_MANAGER { get; set; }
        public Nullable<int> MN_PROJECTION { get; set; }
        public Nullable<decimal> JOB_VOWD { get; set; }
        public Nullable<decimal> JOB_PVOWD { get; set; }
        public Nullable<int> MN_CLOSE { get; set; }
        public Nullable<int> BP_OFFSHORE { get; set; }
        public string CLIENT { get; set; }
        public string LOCATION { get; set; }
        public Nullable<decimal> OT_PERCENT { get; set; }
        public Nullable<decimal> FUEL_PERCENT { get; set; }
        public Nullable<decimal> FOOD_STAFF { get; set; }
        public Nullable<decimal> FOOD_WORKER { get; set; }
        public string JOBTP { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BP_ADJYEAR> TBL_BP_ADJYEAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BP_RESOURCE> TBL_BP_RESOURCE { get; set; }
    }
}
