//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BP_RESOURCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_BP_RESOURCE()
        {
            this.TBL_BP_RESOURCE_ = new HashSet<TBL_BP_RESOURCE_>();
        }
    
        public int BP_YEAR { get; set; }
        public string JOB_NO { get; set; }
        public string RESO_GROUP { get; set; }
        public string RESO_ID { get; set; }
        public string RESO_TYPE { get; set; }
        public string RESO_DESCRIPTION { get; set; }
        public string RESO_UNIT { get; set; }
        public Nullable<decimal> RESO_RATE { get; set; }
        public Nullable<decimal> RESO_EQTY { get; set; }
        public Nullable<decimal> ROW_ID { get; set; }
    
        public virtual TBL_BP_DICTIONARY TBL_BP_DICTIONARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BP_RESOURCE_> TBL_BP_RESOURCE_ { get; set; }
    }
}
