//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MN_PROVISION
    {
        public decimal PROV_ID { get; set; }
        public string JOB_NO { get; set; }
        public string ITM_ID { get; set; }
        public string ITM_TYPE { get; set; }
        public int ITM_YEAR { get; set; }
        public int ITM_MONTH { get; set; }
        public string PROV_DESCRIPTION { get; set; }
        public Nullable<decimal> PROV_OPNBAL { get; set; }
        public string PROV_OFORMULA { get; set; }
        public Nullable<decimal> PROV_VALUE { get; set; }
        public string PROV_VFORMULA { get; set; }
        public string PROV_ACCNO { get; set; }
    }
}
