//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BP_POSTED
    {
        public string PORA { get; set; }
        public Nullable<int> POST_YEAR { get; set; }
        public Nullable<int> POST_MONTH { get; set; }
        public Nullable<int> POST_STATUS { get; set; }
    }
}
