//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BP_REVISION
    {
        public string JOB_NO { get; set; }
        public string ITM_ID { get; set; }
        public string ITM_TYPE { get; set; }
        public int ITM_YEAR { get; set; }
        public int ITM_MONTH { get; set; }
        public Nullable<decimal> ITM_VALUE { get; set; }
        public string ITM_FORMULA { get; set; }
    }
}
