//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MN_USERMAP
    {
        public string NT_USER { get; set; }
        public string JOB_NO { get; set; }
        public Nullable<int> CLASS { get; set; }
        public string BP_USER { get; set; }
    }
}
