//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MN_LOGAPPROVAL
    {
        public string JOB_NO { get; set; }
        public int POST_MONTH { get; set; }
        public int POST_YEAR { get; set; }
        public Nullable<int> PM_STATUS { get; set; }
        public Nullable<System.DateTime> PM_DATE { get; set; }
        public Nullable<int> HD_STATUS { get; set; }
        public Nullable<System.DateTime> HD_DATE { get; set; }
        public Nullable<int> FT_STATUS { get; set; }
        public Nullable<System.DateTime> FT_DATE { get; set; }
    }
}
