//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MN_POSTED
    {
        public string JOB_NO { get; set; }
        public int ITM_YEAR { get; set; }
        public int ITM_MONTH { get; set; }
        public Nullable<int> ITM_POSTED { get; set; }
    }
}
