//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MN_HEADS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MN_HEADS()
        {
            this.TBL_MN_ACTUALS = new HashSet<TBL_MN_ACTUALS>();
            this.TBL_MN_BPLAN = new HashSet<TBL_MN_BPLAN>();
            this.TBL_MN_PROJECTION = new HashSet<TBL_MN_PROJECTION>();
        }
    
        public string ITM_ID { get; set; }
        public string ITM_TYPE { get; set; }
        public string ITM_DESCRIPTION { get; set; }
        public Nullable<decimal> ROW_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MN_ACTUALS> TBL_MN_ACTUALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MN_BPLAN> TBL_MN_BPLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MN_PROJECTION> TBL_MN_PROJECTION { get; set; }
    }
}
