//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOWDH
    {
        public decimal HSNO { get; set; }
        public string JOB_NO { get; set; }
        public string ITM_ID { get; set; }
        public string ITM_TYPE { get; set; }
        public Nullable<int> ITM_YEAR { get; set; }
        public Nullable<int> ITM_MONTH { get; set; }
        public Nullable<decimal> OLD_VALUE { get; set; }
        public Nullable<decimal> NEW_VALUE { get; set; }
        public string CRDBY { get; set; }
        public Nullable<System.DateTime> CRDON { get; set; }
    }
}
